### ISSUE TITLE
Function for reloading modules with keybinding

### ISSUE THREAD

**Issue by tpiekarski** [orhun/kmon#10]
**Is your feature request related to a problem? Please describe.**

It is related to the problem when developing modules, building custom kernels or 
trying to make some proprietary module work. In such cases it is often necessary 
to quickly reload a module (in a followup issue it could be also reloaded with 
different arguments passed to the module).

**Describe the solution you'd like**

The solution could be to provide a function for reloading (unloading and loading) a module
and to offer the keybinding `r` (colliding with refresh, so maybe a `R` or moving refresh to `C^r` like in browsers).

**Describe alternatives you've considered**

None have been considered, because the unloading function currently present is very similar 
and works very well.

**Additional context**

There're a Load and Unload command defined in [ModuleCommand](https://github.com/orhun/kmon/blob/3271a0fe530a1358bb99292b0df848727f876877/src/kernel/cmd.rs#L55) and those would be used together to implement this reload feature. Either as a new function in ModuleCommand or when registering with the [key input event handling](https://github.com/orhun/kmon/blob/ea3469ae00bfa57d51fb247a0eee2b81d5c2f227/src/main.rs#L98) both already present function would be called.

I'd like to provide a PR.

**Comment by orhun** [comment]
It sounds great to assign the `ctrl-r` key to the module reload feature. [Load](https://github.com/orhun/kmon/blob/master/src/kernel/cmd.rs#L65) and [Unload](https://github.com/orhun/kmon/blob/master/src/kernel/cmd.rs#L70) commands could be combined for the new reload command since they will basically follow each other in the execution process. Also, this feature might come in handy in such situations like as you referred.

**Comment by tpiekarski** [comment]
Thanks, so I'll offer a PR for discussion at Monday. Propably I'll need some help with testing 😊
