### ISSUE TITLE
Display dependent modules

### ISSUE THREAD

**Issue by tpiekarski** [orhun/kmon#11]
**Is your feature request related to a problem? Please describe.**
At the moment not all dependent modules are displayed.

**Describe the solution you'd like**
When selecting a module in the kernel modules table all dependent modules could be displayed in module information widget in a list, sorted by name. 
The current display of dependent modules in the kernel modules table could be suffixed with `...`.

**Describe alternatives you've considered**
None, but open for alternatives :smile: 

**Additional context**
None

I'd like to provide a PR.

**Comment by orhun** [comment]
Appending `...` if there are enough dependent modules to exceed the table limit is a good idea. Maybe this could be implemented by comparing the widths of the modules table and dependent modules. On the other hand, showing all the dependent modules with another key binding is a necessity for providing all the information about a specific module. Or a horizontal scrolling feature for the modules table could be implemented but having a key binding is more convenient for sure.
What's in your mind specifically?

**Comment by tpiekarski** [comment]
> [...] Maybe this could be implemented by comparing the widths of the modules table and dependent modules. 

Yes, this sounds good. The position where the width of dependent modules exceeds the available space provided by the column is stored. Than its possible to find the previous space character in that string and at this position the cut will be done and those '...' appended. Like this any module name will be cut.

> On the other hand, showing all the dependent modules with another key binding is a necessity for providing all the information about a specific module. 

Would this key binding show a new widget? Why not showing this information in the present details widget? At the end it could be appended with a heading like 'Dependent modules'.

> Or a horizontal scrolling feature for the modules table could be implemented but having a key binding is more convenient for sure.

Not so much a fan of horizontal scrolling, but indeed that could work out for smaller lists of dependent modules. But for a list with 20+ modules horizontal scrolling could tend to be tedious. 

> What's in your mind specifically?
Cut the list at the closest (to the max column width) space character, append '...' and show all modules sorted by name in a list at the bottom of the present module information widget.

What do you think?

**Comment by orhun** [comment]
> [...] Is there an event we could use to recut that string?

There is the [draw_kernel_modules](https://github.com/orhun/kmon/blob/master/src/app.rs#L286) function in the `app` module which is responsible for rendering/refreshing the module table for every [tickrate] milliseconds. Maybe that could be used.

> Would this key binding show a new widget? Why not showing this information in the present details widget? At the end it could be appended with a heading like 'Dependent modules'.

The module information block (on the right) could be used for showing all the dependent modules. There's no need for a new widget in my opinion.

> Not so much a fan of horizontal scrolling [...]

Me too :sweat_smile: "having a key binding is more convenient for sure"

> Cut the list at the closest (to the max column width) space character, append '...' and show all modules sorted by name in a list at the bottom of the present module information widget.

It's OK if the present blocks (or widgets) will be used. In such case, appending `...` at the end of the `used-by` column (if it exceeds the table width) and showing all the dependent modules with a new key binding would be enough I think.

**Comment by tpiekarski** [comment]
> > [...] Is there an event we could use to recut that string?
> 
> There is the [draw_kernel_modules](https://github.com/orhun/kmon/blob/master/src/app.rs#L286) function in the `app` module which is responsible for rendering/refreshing the module table for every [tickrate] milliseconds. Maybe that could be used.

Thanks, I am going to try using this.

> > Would this key binding show a new widget? Why not showing this information in the present details widget? At the end it could be appended with a heading like 'Dependent modules'.
> 
> The module information block (on the right) could be used for showing all the dependent modules. There's no need for a new widget in my opinion.
> 
> > Not so much a fan of horizontal scrolling [...]
> 
> Me too  "having a key binding is more convenient for sure"

What do you think about introducing `d` as a keybinding which then would show the dependent modules by jumping to the section *Dependent modules* in the present module information widget?

**Comment by orhun** [comment]
> What do you think about introducing `d` as a keybinding which then would show the dependent modules by jumping to the section _Dependent modules_ in the present module information widget?

It sounds good to me. 

Also, here's a picture to make it more concrete:

![z](https://user-images.githubusercontent.com/24392180/79112645-afb2a980-7d87-11ea-954a-9614ec8ae61a.png)

**Comment by tpiekarski** [comment]
That's a good idea with a screen (hope you did not implemented it yet :smile: )
Before implementing that feature I though to briefly rundown for getting last details straight.

### Showing/Hiding dependent modules
1. User selects a module
2. User presses a keybinding like `d` -- **What keybindings should be used?**
3. Kmon displays all dependent modules in a new widget 
   - in place of the current module information widget 
    **Can be present widget reused and the content only exchanged?** 
   - alpha-numerically sorted
4. User presses the same keybinding again to hide the dependent modules widget
(like a toggle for showing / hiding)

### Limiting display of dependent modules in *Loaded Kernel Modules* widget
- `Used-by` column is limited to the visible part by...
  - Finding closest space to the max width of column
  - Making sure that for appending `...` is enough space
**How that should be handled? What do you think to find the second closest space to the max width, to make sure there is enough space left for `...`?**
  - Cutting string at that position
  - Appending `...`
- When terminal window is resized or font size changed this procedure has to run again

Hope I did not miss anything. Looking forward to implement that :smile:

**Comment by orhun** [comment]
> [...] hope you did not implemented it yet [...]

No I didn't implement it :smile: It was just a "hacky" picture to show how things should be.

### Showing/Hiding dependent modules
1. User selects a module :heavy_check_mark: 
2. User presses a keybinding like `d`  :heavy_check_mark: 
**>>** (`d, alt-d` for now, I'll look into that)
3. Kmon displays all dependent modules in a new widget 
   - in place of the current module information widget :heavy_check_mark: 
**>>** Yes, exactly. Only the title and the content will be changed in order to show the dependent modules.
   - alpha-numerically sorted :thinking: 
**>>** I think they should be sorted like they are on the "Loaded Kernel Modules" table for legibility.
4. User presses the same keybinding again to hide the dependent modules widget
(like a toggle for showing / hiding) :thinking: 
**>>** Toggle feature is not necessary. Other key bindings does not have that function.

> Limiting display of dependent modules in *Loaded Kernel Modules* widget
**How that should be handled? What do you think to find the second closest space to the max width, to make sure there is enough space left for `...`? Or dropping the idea of cutting at whitespace and cutting at `max-width - 3` instead? (Maybe this cutting at whitespaces could be something for a subsequent feature)**

Retrieving the max width and the `used-by` column width to compare them to append `...` (after the split from the last-exceeding dependent module) sounds more appropriate to me. If this procedure is handled by a function[*](https://github.com/orhun/kmon/blob/master/src/app.rs#L286) that continuously called in the main terminal loop, resizing or changing the font size won't be a problem since they are re-calculated every time.
I can't say anything technical about the implementation since I have to debug/check the width values and how they are affected. But if you share some of the things that you've tried, maybe I can help further about the implementation.

> Hope I did not miss anything. Looking forward to implement that.

:ok_hand:

**Comment by tpiekarski** [comment]
Thanks for your feedback. Can't wait to start tomorrow when I'm back at my office.
