### ISSUE TITLE
Introduce new sorting argument for most-used module

### ISSUE THREAD

**Issue by tpiekarski** [orhun/kmon#7]
**Is your feature request related to a problem? Please describe.**
Not a problem, but rather an idea. Its about to quickly identify within kmon the most dependent modules which uses most other modules.

**Describe the solution you'd like**
Passing a new command line argument for sorting. Something like:
`kmon sort -d | --dependents` or `kmon sort -u | --used` 
This argument would sort by the column *used by* at /proc/modules (3rd column) and could also be reversed with `-r`.

What do you think? I'd like to provide a PR as well.

**Describe alternatives you've considered**
None. Such sorting is already present for module name and size.

**Additional context**
None.

**Comment by orhun** [comment]
Good idea :+1:  Although kmon cannot show all the _used_ modules because of the table widget size, sorting them might be helpful.
Also, I'm not sure about the **cleanest** way of implementing this but an additional command can be used as I've used for the [other sorting types](https://github.com/orhun/kmon/blob/master/src/kernel/lkm.rs#L87).

**Comment by tpiekarski** [comment]
Thanks. I'll implement this feature today like other sorting types and push a PR.

What do you think due to the limited widget size to append a `...` or `... see details widget` and there kmon lists them all below the current displayed information? But probably this is going to be another feature issue.

**Comment by orhun** [comment]
That would be another good feature for showing all the used modules. You can always open another feature issue to discuss it there.
